---
always_allow_html: yes
classoption: landscape
graphics: yes
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
output: word_document
---

```{r, include=FALSE}
library(dplyr)
library(kableExtra)
library(formattable)
library(sparkline)
library(webshot)
library(htmltools)
```

```{r echo = FALSE}
SelectedDtaCNCL <- SelectedDtaCNCL()
        SelectedDtaCNCL <- select(SelectedDtaCNCL, -Local.Authority, -Domain)
        SelectedDtaCNCL <- arrange(SelectedDtaCNCL, Indicator, Year)
        indis <- unique(SelectedDtaCNCL$Indicator)
        lstGrps <- c()
        for(i in 1:length(indis)){
          rws <- sum(SelectedDtaCNCL$Indicator == indis[i])
          names(rws) <- indis[i]
          lstGrps <- c(lstGrps, rws)
        }
        grph <- select(SelectedDtaCNCL, c("Year","Indicator", "Ranking")) %>%
          mutate(maxt = 32) %>%
          gather(Indi, values, c("Ranking", "maxt")) %>%
          group_by(Indicator, Year) %>%
          dplyr::summarise(grphs = spk_chr(
            values, type = "bullet", width = "100"
          ))
        grph <- dplyr::arrange(grph, Indicator, Year)
        SelectedDtaCNCL$grphs <- grph$grphs
        
        f <- formattable(SelectedDtaCNCL[-1])
#          group_rows(index = lstGrps) %>%
#          kable_styling(position = "left") %>%
#          htmltools::HTML() %>%
#          shiny::div() %>%
#          sparkline::spk_add_deps()

        export_formattable <- function(f, file, width = "100%", height = NULL, 
                               background = "white", delay = 0.2)
    {
      w <- as.htmlwidget(f, width = width, height = height) %>% sparkline::spk_add_deps()
      path <- html_print(w, background = background, viewer = NULL)
      url <- paste0("file:///", gsub("\\\\", "/", normalizePath(path)))
      webshot(url,
              file = file,
              selector = ".formattable_widget",
              delay = delay)
        }
        export_formattable(f, "test.pdf")
        
```
